

NIVEL_MAGICO_DOCENCIO = (40, 60)
DESTREZA_DOCENCIO = (30, 40)
ENERGIA_DOCENCIO = (40, 50)
RESPONSABILIDAD_DOCENCIO = (15, 20)


NIVEL_MAGICO_TAREO = (40, 55)
DESTREZA_TAREO = (40, 50)
ENERGIA_TAREO = (35, 45)
RESPONSABILIDAD_TAREO = (10, 25)

NIVEL_MAGICO_HIBRIDO = (35, 45)
DESTREZA_HIBRIDO = (30, 50)
ENERGIA_HIBRIDO = (50, 55)
RESPONSABILIDAD_HIBRIDO = (15, 25)

PRECIO_AUGUREY = 75
PRECIO_NIFFLER = 125
PRECIO_ERKLING = 125

NIVEL_MAGICO_AUGUREY = (20, 25)
PUNTOS_SALUD_AUGUREY = (35, 45)
PROBABILIDAD_ESCAPE_AUGUREY = 0.2
PROBABILIDAD_ENFERMARSE_AUGUREY = 0.3
MAX_DIAS_SIN_COMER_AUGUREY = 3
NIVEL_AGRESIVIDAD_AUGUREY = "inofensiva"

NIVEL_MAGICO_NIFFLER = (10, 20)
PUNTOS_SALUD_NIFFLER = (20, 30)
PROBABILIDAD_ESCAPE_NIFFLER = 0.3
PROBABILIDAD_ENFERMARSE_NIFFLER = 0.2
MAX_DIAS_SIN_COMER_NIFFLER = 2
NIVEL_AGRESIVIDAD_NIFFLER = "arisca"
NIVEL_CLEPTO_NIFFLER = (5, 10)

NIVEL_MAGICO_ERKLING = (30, 45)
PUNTOS_SALUD_ERKLING = (50, 60)
PROBABILIDAD_ESCAPE_ERKLING = 0.5
PROBABILIDAD_ENFERMARSE_ERKLING = 0.3
MAX_DIAS_SIN_COMER_ERKLING = 2
NIVEL_AGRESIVIDAD_NIFFLER = "peligrosa"


PRECIO_TARTA_DE_MELAZA = 10
PRECIO_HIGADO_DE_DRAGON = 15
PRECIO_BUÑUELO_DE_GUSARAJO = 3

sickles_iniciales = 500

magos = {
    "0": "Docencio",
    "1": "Tareo",
    "2": "Hibrido"
}

atr_mag = { # atributos de magizoologos
    "dccriaturas": ["Augurey", "Niffler", "Erkling"],
    "alimentos": ["Tarta de Melaza", "Hígado de Dragón", "Buñuelo de Gusarajo"],
    "nivel_magico": [NIVEL_MAGICO_DOCENCIO, NIVEL_MAGICO_TAREO, NIVEL_MAGICO_HIBRIDO],
    "destreza": [DESTREZA_DOCENCIO, DESTREZA_TAREO, DESTREZA_HIBRIDO],
    "energia_total": [ENERGIA_DOCENCIO, ENERGIA_TAREO, ENERGIA_HIBRIDO],
    "responsabilidad": [RESPONSABILIDAD_DOCENCIO, RESPONSABILIDAD_TAREO, RESPONSABILIDAD_HIBRIDO]
}
